steps:
  # Instalar dependencias
  - name: 'node:20'
    entrypoint: 'sh'
    args: 
      - '-c'
      - 'corepack enable && pnpm install'
    dir: 'frontend'
    id: 'install-dependencies'

  # Construir el proyecto Next.js (exportación estática)
  - name: 'node:20'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'corepack enable && pnpm run build'
    dir: 'frontend'
    id: 'build-frontend'
    waitFor: ['install-dependencies']

  # Subir archivos al bucket de Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-c'
      - '-d'
      - 'frontend/out/'
      - 'gs://frontend-agentsupportops-prod/'
    id: 'upload-to-gcs'
    waitFor: ['build-frontend']

  # Configurar metadatos para archivos web
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'setmeta'
      - '-h'
      - 'Cache-Control:public, max-age=3600'
      - '-r'
      - 'gs://frontend-agentsupportops-prod/**'
    id: 'set-cache-headers'
    waitFor: ['upload-to-gcs']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

timeout: '1200s'
